run:
  skip-dirs:
    - internal/addrs
    - internal/config
    - internal/configs

linters:
  enable-all: false
  enable:
    - deadcode
    - errcheck
    - gofmt
    - golint
    - gosec
    - govet
    - ineffassign
    - interfacer
    - lll
    - megacheck
    - misspell
    - nakedret
    - structcheck
    - unconvert
    - varcheck
