name: golangci-lint
on:
  push:
    branches:
      - master
    paths-ignore:
      - CHANGELOG.md
    tags-ignore:
      - v*
      - sdk/*
      - '**'
  pull_request:
    branches:
      - master
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
          cache-dependency-path: |
            **go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true
